project:
  type: book
  output-dir: _book

book:
  title: "Kompendier"
  reader-mode: true
  page-footer:
    left: |
      Kompendier i Geofag 2 er skrevet av Elisabeth Engum
    right: |
      Innholdet er tilpasset Geofag 2 etter LK20
  author: "Elisabeth Engum"
  date: today
  search: true
  repo-url: https://github.com/PGelisa/pgelisa.github.io
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  repo-branch: main
  repo-actions: [edit, issue]
  
  page-navigation: true
  sidebar:
    style: docked
    background: light
    
  chapters:
    - index.qmd
    - intro.qmd
    - Ulikheter.ipynb
    
    
    

bibliography: 
  - references.bib

format:
  html:
    theme: 
      - cosmo
      - pgelisa.scss
    author-meta: "PGelisa på tur"
    callout-appearance: simple
  pdf:
    documentclass: scrreprt

editor: visual

